Fix call to usage which requires an int argument
Otherwise compilation fails:

main.c: In function ‘main’:
main.c:158:7: error: too few arguments to function ‘usage’
       usage();
       ^~~~~
main.c:73:14: note: declared here
 static void  usage(int status) _CUPS_NORETURN;
              ^~~~~
make[1]: *** [../Makedefs:270: main.o] Error 1