tls-gnutls: Make loop variable `unsigned integer`
Fix the error below (gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0
20160609):

    Compiling tls.c...
    In file included from tls.c:39:0:
    tls-gnutls.c: In function ‘httpCredentialsAreValidForName’:
    tls-gnutls.c:420:56: error: conversion to ‘int’ from ‘unsigned int’ may change the sign of the result [-Werror=sign-conversion]
               if (!gnutls_x509_crl_get_crt_serial(tls_crl, (unsigned)i, rserial, &r
                                                            ^

Revert commit 163a773e (Fix compiler warning.).

Fixes: https://github.com/apple/cups/issues/5532