Add missing include
This fixes the build for the case where
'HAVE_LIBPAM' is 0.

(Previous build error:
"auth.c:2017:5: error: unknown type name '_cups_md5_state_t';
did you mean '_cups_message_t'?".)